create table teams
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table teams
    owner to postgres;

create index idx_team_name
    on teams (name);

create table users
(
    id        varchar(255) not null
        primary key,
    is_active boolean      not null,
    name      varchar(255) not null,
    team_id   bigint       not null
        constraint fkfjws1rdruab2bqg7qipoqf65r
            references teams
);

alter table users
    owner to postgres;

create table pull_requests
(
    id        varchar(255) not null
        primary key,
    merged_at timestamp(6) with time zone,
    title     varchar(255) not null,
    status    varchar(255) not null
        constraint pull_requests_status_check
            check ((status)::text = ANY ((ARRAY ['OPEN'::character varying, 'MERGED'::character varying])::text[])),
    author_id varchar(255)
        constraint fka8oqol0kr7gh7ut27byc1wywb
            references users
);

alter table pull_requests
    owner to postgres;

create table pull_request_reviewers
(
    pull_request_id varchar(255) not null
        constraint fko67jt1vdmauue5pbmybmx908s
            references pull_requests,
    reviewer_id     varchar(255) not null
        constraint fkth9cswar1jtppe8ovubnkgre4
            references users
);

alter table pull_request_reviewers
    owner to postgres;
